version: '3.9'
networks:
  default:
    name: startnode-app-net
    driver: bridge
services:
  bot-app:
    networks:
      - default
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${APP_PORT}:${APP_PORT}
    environment:
      APP_PORT: ${APP_PORT}
      MONGO_HOSTNAME: ${MONGO_HOSTNAME}
      MONGO_PORT: ${MONGO_PORT}
  db-mongo:
    networks:
      - default
    image: mongo
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}

  mongo-express:
    image: mongo-express
    networks:
      - default
    ports:
      - '8080:8081'
    environment:
      ME_CONFIG_MONGODB_SERVER: ${MONGO_HOSTNAME}
      ME_CONFIG_MONGODB_PORT: ${MONGO_PORT}
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_PASSWORD}

